<?php
# Get credentials
include('guard.php');
include_once('get-group-password.php');
# Credentials
$host = 'localhost';
$db = 'CS_2022_Spring_3430_101_t1';
$user = 'joneshl4';
$password = $GLOBALS['group-sql-password'];

# Data source name and connect!
$dsn = "mysql:host=$host;dbname=$db;charset=UTF8";
try
{
    $pdo = new PDO($dsn, $user, $password);
}
catch (PDOException $e)
{
    die("Could not connect to the database. Contact a sysadmin with this: " + $e->getMessage());
}

# Safety
$password = $user = $db = $host = '';

# Prepare some queries to get information based on ids from the database
$idqueryproduct = $pdo->prepare('SELECT productId, name, cost FROM project_product WHERE productId = ?');
$idqueryproduct->setFetchMode(PDO::FETCH_ASSOC);
$idqueryrentee = $pdo->prepare('SELECT * FROM RenteeUnauth WHERE userId = ?');
$idqueryrentee->setFetchMode(PDO::FETCH_ASSOC);
$idqueryrenter = $pdo->prepare('SELECT * FROM RenterUnauth WHERE userId = ?');
$idqueryrenter->setFetchMode(PDO::FETCH_ASSOC);

# Define methods to use $pdo easily
function get_object_by_uuid($id)
{
    # So many globals aghhhh!
    global $pdo, $idqueryproduct, $idqueryrentee, $idqueryrenter;
    $idqueryproduct->execute(array($id));
    $result = $idqueryproduct->fetchAll()[0];
    # Run this for every table. This looks generated by an online service but is unfortunately not.
    if (isset($result['productId']))
    {
        return $result + array('type' => 'product');
    }
    $idqueryrentee->execute(array($id));
    $result = $idqueryrentee->fetchAll()[0];
    # Don't call idquery2 intelligently, that's not intelligent at all
    # We tried using two queries but it didn't work--would have been slower anyway
    if (isset($result['userId']))
    {
        return $result + array('type' => 'renter');
    }
    # One last one. I need sleep.
    $idqueryrenter->execute(array($id));
    $result = $idqueryrenter->fetchAll()[0];
    if (isset($result['userId']))
    {
        return $result + array('type' => 'rentee');
    }
    return NULL;
}

# Get for hybrid search and stuff by building lots of strings
$cols = 'SELECT * FROM ';
$profile_name = ' WHERE profileName LIKE ?';
$name = ' WHERE name LIKE ?';
$filter_profile_name = ' ORDER BY profileName';
$filter_name = ' ORDER BY name';
$filter_continued = ' DESC OFFSET ? ROWS FETCH NEXT ? ROWS ONLY';
$search_query_rentee = $pdo->prepare($cols . 'RenteeUnauth' . $profile_name . $filter_profile_name . $filter_continued);
$search_query_rentee->setFetchMode(PDO::FETCH_ASSOC);
$search_query_renter = $pdo->prepare($cols . 'RenteeUnauth' . $profile_name . $filter_profile_name . $filter_continued);
$search_query_renter->setFetchMode(PDO::FETCH_ASSOC);
$search_query_product = $pdo->prepare($cols . 'project_product' . $name . $filter_name . $filter_continued);
$search_query_product->setFetchMode(PDO::FETCH_ASSOC);
# Get an object's information by its keywords
function get_object_by_keywords($kw, $count, $offset)
{
    global $search_query_rentee, $search_query_renter, $search_query_product;
    $inputs = array($kw, $offset, $count);
    $results = array();
    $search_query_rentee->execute($inputs);
    $results->rentees = $search_query_rentee->fetchAll();
    $search_query_renter->execute($inputs);
    $results->renters = $search_query_renter->fetchAll();
    $search_query_product->execute($inputs);
    $results->product = $search_query_product->fetchAll();
    return $results;
}

?>
